config/routes.rb
Rails.application.routes.draw do

  root 'patient#index'
  resources  :patient

end

app/models/appoinment.rb
class Appoinment < ActiveRecord::Base
   belongs_to :patient
   belongs_to :physician
end

app/models/patient.rb
class Patient < ActiveRecord::Base
	has_many :appoinments
	has_many :patients, through: :appoinments
end

app/models/physician.rb
class Physician < ActiveRecord::Base
	has_many :appoinments
	has_many :patients, through: :appoinments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/patient_controller.rb
class PatientController < ApplicationController
	
	def index
	end

	def create
	end

	def new
	end

	def show
	end

	def edit
	end

	def delete
	end

	def update
	end

end

app/controllers/physician_controller.rb
class PhysicianController < ApplicationController
	def index
	end

	def create
	end

	def new
	end

	def show
	end

	def edit
	end

	def delete
	end

	def update
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HospitalInfo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/patient/index.html.erb
<%= link_to "New Patient" , new_patient_path %>

app/views/patient/new.html.erb
<%= form_tag({:controller=>"patient",:action=> "create"}, method: :post) do |f| %>
     <%= label_tag(:name, "Enter Patient_name") %>		
     <%= text_field_tag(:name,:name) %>
     <%= submit_tag("Search") %>
<% end %>